CREATE TABLE "Conversations" (
  "id" SERIAL PRIMARY KEY,
  "favorite_list" BOOLEAN[] DEFAULT ARRAY[FALSE],
  "black_list" BOOLEAN[] DEFAULT ARRAY[FALSE],
  "participants" INT[] NOT NULL,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Messages" (
  "id" SERIAL PRIMARY KEY,
  "sender_id" INT REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "body" TEXT NOT NULL,
  "conversation_id" INT REFERENCES "Conversations"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Catalogs" (
  "id" SERIAL PRIMARY KEY,
  "user_id" INT REFERENCES "Users"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "catalog_name" VARCHAR(255) UNIQUE NOT NULL,
  "chats" INT[] NOT NULL,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);