# version: '3.8'
services:

  front-react:
    build:
      context: ./client
    environment:
      NODE_ENV: development
      # REACT_APP_DOCKER_ENV: true
    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "5000:3000"
    # networks:
    #   - app-network

  server-dev:
    build:
      context: ./server
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db-dev
    volumes:
      - ./var/www/html/images:/var/www/html/images
      - ./server:/server
      - /server/node_modules
    # command: sh -c "until pg_isready -h db-dev -p 5432 -U postgres; do echo 'Waiting for database...'; sleep 2; done && npx sequelize db:migrate && npx sequelize db:seed:all && npm start"
    # networks:
    #   - app-network

  db-dev:
    image: postgres:15.5-bullseye
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-dev
    ports:
      - "12346:5432"
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge